### ISSUE TITLE
The ratio between a `Color` and a `float` is incorrect

### ISSUE THREAD

**Issue by ziotom78** [teozec/image-renderer#18]
The code that implements the [operation `Color / float`](https://github.com/teozec/image-renderer/blob/pathtracing/include/color.h#L51) is incorrect:

```c++
Color operator/(const float c) {
    return Color{c/r, c/g, c/b};
}
```

as it computes `float / Color` (the inverse). This is not spotted in the [tests for `Color`](https://github.com/teozec/image-renderer/blob/pathtracing/test/color.cpp), as they only cover sums and products.

This will probably fix the failing test on the path-tracing algorithm.

**Comment by teozec** [comment]
Thank you very much for your contribution! This was corrected in #19, and it also fixed the path-tracing test as you suggested.
